### ISSUE TITLE
[BUG] Weird color change between different fog tones (affect to texture world)

### ISSUE THREAD

**Issue by Sol1vaN** [InsanityBringer/PiccuEngine#29]
Hi there,

In Piccu Station & SRAD Research map (I recently noticed the name source of this source port, lol).
...in the caverns stage, there's two colored fogs (light blue and violet).
It seems that there's conflict with zbuffer or something that affect the transition between the two fog colors.
This bug affect only to the texture world, heres the video showing this bug:

https://youtu.be/1727m6x3uHc

I don't know if this is present in original Descent ³ 1.4 or 1.5
Cheers.

**Comment by InsanityBringer** [comment]
Piccu Station has some odd fog anomalies, the worst can be spied in the lava rooms. Here's a pic from an earlier build of Piccu
![image](https://github.com/InsanityBringer/PiccuEngine/assets/1504999/660bcaad-f5b2-45f3-8315-ecb2f8908eac)
So far as I can tell, this is a vanilla bug, but I'd like to figure out why it happens since it looks pretty bad.

**Comment by InsanityBringer** [comment]
Closing this because it's addressed in Newrender, though I'll probably backport the fix to legacy if I can.

overall the fog in this level is pretty poorly set up, but adding a clamp to the fog magnitude fixes this particular problem, and some anomalies that can be spied in other levels (level 2's hazardous waste room is pretty bad too)
